GET http://localhost:3000/api/task
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NmUyNzdkZjk5NDJlNTAyYzJiNWUwNSIsIm5hbWUiOiJMdWPDrWEgR8OzbWV6IiwidXNlcm5hbWUiOiJsZ29tZXoiLCJ0eXBlT2ZVc2VyIjoiw6FyZWEiLCJpYXQiOjE3MTg1MjA4NzJ9.GaM8aHoplmG9IjAgdR4qMYNhx2bPDvsOAVZNfrK6c-U